#include <iostream>
#include <new>
#include <cstdlib>


//功能：15.13 异常（bad_alloc异常和new）
//时间：2020年12月6日10:28:15
//using namespace std;
//
//struct Big
//{
//	double stuff[20000];
//};
//
//
//
//int main()
//{
//	Big* pb;
//
//	try
//	{
//		cout << "Trying to get a big block of memory:\n";
//		pb = new Big[10000];
//		cout << "Got past the new request:\n";
//	}
//	catch (bad_alloc & ba)
//	{
//		cout << "Caught the exception!\n";
//		cout << ba.what() << endl;
//		exit(EXIT_FAILURE);
//	}
//
//	cout << "Memory successfully allocated!\n";
//	pb[0].stuff[0] = 4;
//	cout << pb[0].stuff[0] << endl;
//	delete[] pb;
//
//
//	system("pause");
//	return 0;
//}




/*
在x86编译环境下，运行结果如下：（每一个指针占用了四个字节的大小）

-------------------------------------------------------------------------
在x64编译环境下，运行结果如下：（每一个指针占用了八个字节的大小）
*/